version: "2"
checks:
  argument-count:
    config:
      threshold: 10
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 500
  method-complexity:
    config:
      threshold: 12
  method-count:
    config:
      threshold: 40
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4

engines:
  # ... CONFIG CONTENT ...
  checkstyle:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      com.puppycrawl.tools.checkstyle.checks.sizes.LineLengthCheck:
        enabled: false
# ... CONFIG CONTENT ...